backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  
  - name: "photo"
    label: "Photo"
    folder: "content/photos"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Category", name: "category", widget: "relation", collection: "categories", value_field: "title", search_fields: ["title"] }
  - name: "category"
    label: "Category"
    folder: "content/categories"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
  - name: "pricing"
    label: "Pricing"
    folder: "content/pricing"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: string }
      - { label: "Description", name: "description", widget: string }
      - { label: "Price", name: "price", widget: number }
