backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "page"
    label: "Page"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Slogan", name: "slogan", widget: "string" }
        - { label: "Background Image", name: "background_image", widget: "image" }
    - label: "Contact"
      name: "contact"
      file: "content/contact.md"
      fields:
        - { label: "Message", name: "message", widget: "string" }
  - name: "photo"
    label: "Photo"
    folder: "content/photos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      # - {
      #     label: "Category",
      #     name: "category",
      #     widget: "relation",
      #     collection: "meta",
      #     file: "categories",
      #     searchFields: "categories.*.name",
      #     displayFields: "categories.*.name",
      #     valueField: "categories.*.slug"
      #   }
      - { label: "Published At", name: "published_at", widget: "date" }
  - name: "meta"
    label: "Meta"
    files:
      - label: "Categories"
        name: "categories"
        file: "content/meta/categories.md"
        fields:
          - label: "Categories"
            name: "categories"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
  - name: "pricing"
    label: "Pricing"
    folder: "content/pricing"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: string }
      - { label: "Description", name: "description", widget: string }
      - { label: "Price", name: "price", widget: number, required: false }
