backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "page"
    label: "Page"
    folder: "content/pages"
    slug: "{{slug}}"
    fields:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
  - name: "photo"
    label: "Photo"
    folder: "content/photos"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Category", name: "category", widget: "relation", collection: "categories", value_field: "title", search_fields: ["title"] }
  - name: "category"
    label: "Category"
    folder: "content/categories"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
  - name: "pricing"